version: "3"
services:
  mysql:
    image: mysql:5.7
    networks:
      - dbnet
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/fof/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "apple"
  pma:
    image: phpmyadmin/phpmyadmin:4.9
    ports:
      - "8080:80"
    environment:
      PMA_HOST: "mysql"
      PMA_PORT: "3306"
    networks:
      - dbnet
  # discordstats:
  #   image: fofgaming/discordstats
  #   environment:
  #     - DISCORD_BOT_TOKEN
  #     - DB_CONNECTION_STRING
  #   networks:
  #     - dbnet

networks:
  dbnet:

volumes:
  dbdata: